### ISSUE TITLE
5.1 bug FlowGraph

### ISSUE THREAD

**Issue by Anafeyka** [StudioSyndiCatCaius/OmegaGameFramework#9]
In version 5.1.1 the bug
New flow nodes are not displayed in the flow assets palette.

**Comment by StudioSyndiCatCaius** [comment]
Should be fixed in the new 1.3.1 release. Will need a bit more time to push it to "main".

**Comment by Anafeyka** [comment]
In 5.1.1 they are still not added to the palette. And if you make them in 5.0 version and make FlowAsset with these new nodes. They will be displayed in the flow event graph itself in 5.1.1 and will even work.

The problem is somewhere, in the FlowEditor code.

**Comment by StudioSyndiCatCaius** [comment]
Just to clarify, did you use the version that I just uploaded yesterday afternoon? https://github.com/StudioSyndiCatCaius/OmegaGameFramework/releases/tag/1.3.1

**Comment by Anafeyka** [comment]
> Just to clarify, did you use the version that I just uploaded yesterday afternoon? https://github.com/StudioSyndiCatCaius/OmegaGameFramework/releases/tag/1.3.1

Yes!
I think I can give you the logs from VS and UE

VS
```
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\OmegaGameFramework\Private\Widget\DataWidget.cpp(119): warning C4996: 'UWidget::bIsEnabled': Direct access to bIsEnabled is deprecated. Please use the getter or setter. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\Unreal5_1\UE_5.1\Engine\Source\Runtime\AssetRegistry\Public\AssetRegistryModule.h(6): warning : #include AssetRegistry/AssetRegistryModule.h instead of AssetRegistryModule.h

D:\Proj_OGF\Plugins\OmegaGameFramework\Source\OmegaGameFramework\Private\Gameplay\CombatantComponent.cpp(187): warning C4996: 'UKismetTextLibrary::Conv_FloatToText': This method has been deprecated and will be removed. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\OmegaGameFramework\Private\Gameplay\CombatantComponent.cpp(204): warning C4996: 'UKismetTextLibrary::Conv_FloatToText': This method has been deprecated and will be removed. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.

D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Asset\FlowAssetEditor.cpp(114): warning C4996: 'FEditorStyle::GetStyleSetName': FEditorStyle::GetStyleSetName() is deprecated, use FAppStyle::GetAppStyleSetName() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Asset\FlowAssetEditor.cpp(119): warning C4996: 'FEditorStyle::GetStyleSetName': FEditorStyle::GetStyleSetName() is deprecated, use FAppStyle::GetAppStyleSetName() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Asset\FlowAssetEditor.cpp(124): warning C4996: 'FEditorStyle::GetStyleSetName': FEditorStyle::GetStyleSetName() is deprecated, use FAppStyle::GetAppStyleSetName() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Asset\FlowAssetToolbar.cpp(121): warning C4996: 'FEditorStyle::Get': FEditorStyle::Get() is deprecated, use FAppStyle::Get() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Asset\FlowAssetToolbar.cpp(122): warning C4996: 'FEditorStyle::GetBrush': FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Asset\FlowAssetToolbar.cpp(124): warning C4996: 'FEditorStyle::Get': FEditorStyle::Get() is deprecated, use FAppStyle::Get() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\FlowEditorCommands.cpp(28): warning C4996: 'FEditorStyle::GetStyleSetName': FEditorStyle::GetStyleSetName() is deprecated, use FAppStyle::GetAppStyleSetName() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\FlowEditorCommands.cpp(53): warning C4996: 'FEditorStyle::GetStyleSetName': FEditorStyle::GetStyleSetName() is deprecated, use FAppStyle::GetAppStyleSetName() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\FlowEditorCommands.cpp(71): warning C4996: ANY_PACKAGE has been deprecated. Either use full path name of objects (including classes) or provide a valid Outer for *FindObject* functions Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\FlowEditorCommands.cpp(119): warning C4996: 'FEditorStyle::GetStyleSetName': FEditorStyle::GetStyleSetName() is deprecated, use FAppStyle::GetAppStyleSetName() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\Unreal5_1\UE_5.1\Engine\Source\Runtime\AssetRegistry\Public\AssetRegistryModule.h(6): warning : #include AssetRegistry/AssetRegistryModule.h instead of AssetRegistryModule.h
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\FlowGraphSchema.cpp(395): warning C4996: 'FARFilter::ClassNames': Class names are now represented by path names. Please use ClassPaths. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\FlowGraphSchema.cpp(396): warning C4996: 'FARFilter::ClassNames': Class names are now represented by path names. Please use ClassPaths. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\FlowGraphSchema.cpp(430): warning C4996: 'FAssetData::AssetClass': Class names are now represented by path names. Please use AssetClassPath. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\FlowGraphSchema.cpp(442): warning C4996: ANY_PACKAGE has been deprecated. Either use full path name of objects (including classes) or provide a valid Outer for *FindObject* functions Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\Widgets\SFlowGraphNode.cpp(363): warning C4996: 'FEditorStyle::GetColor': FEditorStyle::GetColor() is deprecated, use FAppStyle::GetColor() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\Widgets\SFlowGraphNode.cpp(374): warning C4996: 'FEditorStyle::GetBrush': FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\Widgets\SFlowGraphNode.cpp(443): warning C4996: 'FEditorStyle::GetBrush': FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\Widgets\SFlowGraphNode.cpp(478): warning C4996: 'FEditorStyle::GetBrush': FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\Widgets\SFlowGraphNode.cpp(501): warning C4996: 'FEditorStyle::Get': FEditorStyle::Get() is deprecated, use FAppStyle::Get() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\Widgets\SFlowPalette.cpp(50): warning C4996: 'FEditorStyle::GetBrush': FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\Widgets\SFlowPalette.cpp(113): warning C4996: 'FEditorStyle::GetBrush': FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\LevelEditor\SLevelEditorFlow.cpp(54): warning C4996: 'FAssetData::ObjectPath': FName asset paths have been deprecated. Use GetSoftObjectPath to get the path this asset will use in memory when loaded or GetObjectPathString() if you were just doing ObjectPath.ToString() Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\MovieScene\FlowSection.cpp(36): warning C4996: 'FEditorStyle::Get': FEditorStyle::Get() is deprecated, use FAppStyle::Get() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\MovieScene\FlowSection.cpp(38): warning C4996: 'FEditorStyle::GetSlateColor': FEditorStyle::GetSlateColor() is deprecated, use FAppStyle::GetSlateColor() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\MovieScene\FlowSection.cpp(69): warning C4996: 'FEditorStyle::GetBrush': FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\MovieScene\FlowSection.cpp(84): warning C4996: 'FEditorStyle::GetWidgetStyle': FEditorStyle::GetWidgetStyle() is deprecated, use FAppStyle::GetWidgetStyle() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\MovieScene\FlowTrackEditor.cpp(79): warning C4996: 'FEditorStyle::GetStyleSetName': FEditorStyle::GetStyleSetName() is deprecated, use FAppStyle::GetAppStyleSetName() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\MovieScene\FlowTrackEditor.cpp(141): warning C4996: ANY_PACKAGE has been deprecated. Either use full path name of objects (including classes) or provide a valid Outer for *FindObject* functions Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\MovieScene\FlowTrackEditor.cpp(147): warning C4996: 'FEditorStyle::GetBrush': FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Nodes\FlowNodeBlueprintFactory.cpp(48): warning C4996: 'FEditorStyle::GetBrush': FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Nodes\FlowNodeBlueprintFactory.cpp(59): warning C4996: 'FEditorStyle::GetBrush': FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Nodes\FlowNodeBlueprintFactory.cpp(72): warning C4996: 'FEditorStyle::GetMargin': FEditorStyle::GetMargin() is deprecated, use FAppStyle::GetMargin() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Nodes\FlowNodeBlueprintFactory.cpp(73): warning C4996: 'FEditorStyle::GetFloat': FEditorStyle::GetFloat() is deprecated, use FAppStyle::GetFloat() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Nodes\FlowNodeBlueprintFactory.cpp(74): warning C4996: 'FEditorStyle::GetFloat': FEditorStyle::GetFloat() is deprecated, use FAppStyle::GetFloat() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Nodes\FlowNodeBlueprintFactory.cpp(79): warning C4996: 'FEditorStyle::GetMargin': FEditorStyle::GetMargin() is deprecated, use FAppStyle::GetMargin() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Nodes\FlowNodeBlueprintFactory.cpp(87): warning C4996: 'FEditorStyle::GetMargin': FEditorStyle::GetMargin() is deprecated, use FAppStyle::GetMargin() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.


D:\Proj_OGF\Plugins\OmegaGameFramework\Source\OmegaGameFramework\Private\Preferences\GamePreferenceSubsystem.cpp(37): warning C4996: 'IAssetRegistry::GetAssetsByClass': Class names are now represented by path names. Please use a version of this function that uses FTopLevelAssetPath. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\OmegaGameFramework\Private\Attributes\LevelingComponent.cpp(150): warning C4996: 'UKismetTextLibrary::Conv_FloatToText': This method has been deprecated and will be removed. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\OmegaGameFramework\Private\Attributes\LevelingComponent.cpp(167): warning C4996: 'UKismetTextLibrary::Conv_FloatToText': This method has been deprecated and will be removed. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\OmegaGameFramework\Private\OmegaGameplayEffect.cpp(148): warning C4996: 'UKismetTextLibrary::Conv_FloatToText': This method has been deprecated and will be removed. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\OmegaData\Private\OmegaDataSubsystem.cpp(24): warning C4996: 'IAssetRegistry::GetAssetsByClass': Class names are now represented by path names. Please use a version of this function that uses FTopLevelAssetPath. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\Proj_OGF\Plugins\OmegaGameFramework\Source\Omega5_GameFeatures\Private\OFunctions_GameFeatures.cpp(12): warning C4996: 'UGameFeaturesSubsystem::GetPluginURLForBuiltInPluginByName': Use GetPluginURLByName instead Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>Done building project "Proj_compil.vcxproj".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

UE

```
LogOutputDevice: Error: === Handled ensure: ===
LogOutputDevice: Error: Ensure condition failed: InFilter.ClassNames.Num() == 0  [File:D:\build\++UE5\Sync\Engine\Source\Runtime\AssetRegistry\Private\AssetRegistry.cpp] [Line: 3072] 
LogOutputDevice: Error: Asset Registry Filter using ClassNames instead of ClassPaths. First class name: "Blueprint"
LogOutputDevice: Error: Stack: 
LogOutputDevice: Error: [Callstack] 0x00007ff82c7ffb28 UnrealEditor-AssetRegistry.dll!UE::AssetRegistry::FAssetRegistryImpl::CompileFilter() [D:\build\++UE5\Sync\Engine\Source\Runtime\AssetRegistry\Private\AssetRegistry.cpp:3072]
LogOutputDevice: Error: [Callstack] 0x00007ff82c8001e1 UnrealEditor-AssetRegistry.dll!UAssetRegistryImpl::CompileFilter() [D:\build\++UE5\Sync\Engine\Source\Runtime\AssetRegistry\Private\AssetRegistry.cpp:3047]
LogOutputDevice: Error: [Callstack] 0x00007ff82c814266 UnrealEditor-AssetRegistry.dll!UAssetRegistryImpl::GetAssets() [D:\build\++UE5\Sync\Engine\Source\Runtime\AssetRegistry\Private\AssetRegistry.cpp:1790]
LogOutputDevice: Error: [Callstack] 0x00007fffa596493a UnrealEditor-FlowEditor.dll!UFlowGraphSchema::GatherFlowNodes() [D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\FlowGraphSchema.cpp:401]
LogOutputDevice: Error: [Callstack] 0x00007fffa596daaf UnrealEditor-FlowEditor.dll!UFlowGraphSchema::GetFlowNodeCategories() [D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\FlowGraphSchema.cpp:202]
LogOutputDevice: Error: [Callstack] 0x00007fffa59aa080 UnrealEditor-FlowEditor.dll!SFlowPalette::UpdateCategoryNames() [D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\Widgets\SFlowPalette.cpp:176]
LogOutputDevice: Error: [Callstack] 0x00007fffa5944e16 UnrealEditor-FlowEditor.dll!SFlowPalette::Construct() [D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Graph\Widgets\SFlowPalette.cpp:107]
LogOutputDevice: Error: [Callstack] 0x00007fffa59518d9 UnrealEditor-FlowEditor.dll!FFlowAssetEditor::CreateWidgets() [D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Asset\FlowAssetEditor.cpp:299]
LogOutputDevice: Error: [Callstack] 0x00007fffa597e80e UnrealEditor-FlowEditor.dll!FFlowAssetEditor::InitFlowAssetEditor() [D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Asset\FlowAssetEditor.cpp:190]
LogOutputDevice: Error: [Callstack] 0x00007fffa594b5a8 UnrealEditor-FlowEditor.dll!FFlowEditorModule::CreateFlowAssetEditor() [D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\FlowEditorModule.cpp:197]
LogOutputDevice: Error: [Callstack] 0x00007fffa598f520 UnrealEditor-FlowEditor.dll!FAssetTypeActions_FlowAsset::OpenAssetEditor() [D:\Proj_OGF\Plugins\OmegaGameFramework\Source\FlowEditor\Private\Asset\AssetTypeActions_FlowAsset.cpp:37]
LogOutputDevice: Error: [Callstack] 0x00007ffff841dc8d UnrealEditor-UnrealEd.dll!UAssetEditorSubsystem::OpenEditorForAsset() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\Subsystems\AssetEditorSubsystem.cpp:402]
LogOutputDevice: Error: [Callstack] 0x00007ffff841e481 UnrealEditor-UnrealEd.dll!UAssetEditorSubsystem::OpenEditorForAssets_Advanced() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\Subsystems\AssetEditorSubsystem.cpp:476]
LogOutputDevice: Error: [Callstack] 0x00007ffff841e28a UnrealEditor-UnrealEd.dll!UAssetEditorSubsystem::OpenEditorForAssets() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\Subsystems\AssetEditorSubsystem.cpp:592]
LogOutputDevice: Error: [Callstack] 0x00007fffa5e267e1 UnrealEditor-ContentBrowserAssetDataSource.dll!ContentBrowserAssetData::EditOrPreviewAssetFileItems() [D:\build\++UE5\Sync\Engine\Plugins\Editor\ContentBrowser\ContentBrowserAssetDataSource\Source\ContentBrowserAssetDataSource\Private\ContentBrowserAssetDataCore.cpp:288]
LogOutputDevice: Error: [Callstack] 0x00007fffa5e26a58 UnrealEditor-ContentBrowserAssetDataSource.dll!ContentBrowserAssetData::EditOrPreviewItems() [D:\build\++UE5\Sync\Engine\Plugins\Editor\ContentBrowser\ContentBrowserAssetDataSource\Source\ContentBrowserAssetDataSource\Private\ContentBrowserAssetDataCore.cpp:308]
LogOutputDevice: Error: [Callstack] 0x00007fffa5e0e3ba UnrealEditor-ContentBrowserAssetDataSource.dll!UContentBrowserAssetDataSource::BulkEditItems() [D:\build\++UE5\Sync\Engine\Plugins\Editor\ContentBrowser\ContentBrowserAssetDataSource\Source\ContentBrowserAssetDataSource\Private\ContentBrowserAssetDataSource.cpp:1238]
LogOutputDevice: Error: [Callstack] 0x00007fffe3af6fdc UnrealEditor-ContentBrowser.dll!SContentBrowser::OnItemsActivated() [D:\build\++UE5\Sync\Engine\Source\Editor\ContentBrowser\Private\SContentBrowser.cpp:3020]
LogOutputDevice: Error: [Callstack] 0x00007fffe3a8fcac UnrealEditor-ContentBrowser.dll!TBaseSPMethodDelegateInstance<0,SContentBrowser,1,void __cdecl(TArrayView<FContentBrowserItem const ,int>,enum EAssetTypeActivationMethod::Type),FDefaultDelegateUserPolicy>::Execute() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:295]
LogOutputDevice: Error: [Callstack] 0x00007fffe3af96d8 UnrealEditor-ContentBrowser.dll!SAssetView::OnListMouseButtonDoubleClick() [D:\build\++UE5\Sync\Engine\Source\Editor\ContentBrowser\Private\SAssetView.cpp:3668]
LogOutputDevice: Error: [Callstack] 0x00007fffe3a9f066 UnrealEditor-ContentBrowser.dll!TBaseSPMethodDelegateInstance<0,SAssetView,1,void __cdecl(TSharedPtr<FAssetViewItem,1>),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:312]
LogOutputDevice: Error: [Callstack] 0x00007fffe39f5f92 UnrealEditor-ContentBrowser.dll!TDelegate<void __cdecl(TSharedPtr<FAssetViewItem,1>),FDefaultDelegateUserPolicy>::ExecuteIfBound<void,0>() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateSignatureImpl.inl:639]
LogOutputDevice: Error: [Callstack] 0x00007fffe3b0fd7d UnrealEditor-ContentBrowser.dll!SListView<TSharedPtr<FAssetViewItem,1> >::Private_OnItemDoubleClicked() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Public\Widgets\Views\SListView.h:1115]
LogOutputDevice: Error: [Callstack] 0x00007fffe3afa18d UnrealEditor-ContentBrowser.dll!STableRow<TSharedPtr<FAssetViewItem,1> >::OnMouseButtonDoubleClick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Public\Widgets\Views\STableRow.h:423]
LogOutputDevice: Error: [Callstack] 0x00007ff82d14ef35 UnrealEditor-Slate.dll!FEventRouter::Route<FReply,FEventRouter::FBubblePolicy,FPointerEvent,<lambda_be18c20258355610e1a03a230227eebb> >() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:412]
LogOutputDevice: Error: [Callstack] 0x00007ff82d1b4c42 UnrealEditor-Slate.dll!FSlateApplication::RoutePointerDoubleClickEvent() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5526]
LogOutputDevice: Error: [Callstack] 0x00007ff82d1a4372 UnrealEditor-Slate.dll!FSlateApplication::ProcessMouseButtonDoubleClickEvent() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5511]
LogOutputDevice: Error: [Callstack] 0x00007ff82d19a788 UnrealEditor-Slate.dll!FSlateApplication::OnMouseDoubleClick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5474]
LogOutputDevice: Error: [Callstack] 0x00007ff8329c1967 UnrealEditor-ApplicationCore.dll!FWindowsApplication::ProcessDeferredMessage() [D:\build\++UE5\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:2223]
LogOutputDevice: Error: [Callstack] 0x00007ff8329a67d1 UnrealEditor-ApplicationCore.dll!FWindowsApplication::DeferMessage() [D:\build\++UE5\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:2726]
LogOutputDevice: Error: [Callstack] 0x00007ff8329c4391 UnrealEditor-ApplicationCore.dll!FWindowsApplication::ProcessMessage() [D:\build\++UE5\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:1895]
LogOutputDevice: Error: [Callstack] 0x00007ff83299ff93 UnrealEditor-ApplicationCore.dll!FWindowsApplication::AppWndProc() [D:\build\++UE5\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:925]
LogOutputDevice: Error: [Callstack] 0x00007ff8565ce858 USER32.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8565ce4ee USER32.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x0000022224a57e59 InkObj.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff84f261028 atlthunk.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8565ce858 USER32.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8565ce299 USER32.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8329c5849 UnrealEditor-ApplicationCore.dll!FWindowsPlatformApplicationMisc::PumpMessages() [D:\build\++UE5\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsPlatformApplicationMisc.cpp:142]
LogOutputDevice: Error: [Callstack] 0x00007ff725497332 UnrealEditor.exe!FEngineLoop::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5293]
LogOutputDevice: Error: [Callstack] 0x00007ff7254b287d UnrealEditor.exe!GuardedMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:202]
LogOutputDevice: Error: [Callstack] 0x00007ff7254b296a UnrealEditor.exe!GuardedMainWrapper() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:107]
LogOutputDevice: Error: [Callstack] 0x00007ff7254b5680 UnrealEditor.exe!LaunchWindowsStartup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:244]
LogOutputDevice: Error: [Callstack] 0x00007ff7254c71b4 UnrealEditor.exe!WinMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:282]
LogOutputDevice: Error: [Callstack] 0x00007ff7254ca516 UnrealEditor.exe!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
LogOutputDevice: Error: [Callstack] 0x00007ff856e77614 KERNEL32.DLL!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8573a26a1 ntdll.dll!UnknownFunction []
```

**Comment by Anafeyka** [comment]
Feedback
The latest major version 23.6.6 is built under 5.1.1, custom nodes are displayed. Tested on 3 versions of UE, including custom!

For 5.2.
You need to update the FileSDK module from their main repository.

I also replaced 2 files from the main FlowGraph repository

FlowDiffControl.h
FlowDiffControl.cpp.

Everything works, but I only tested this on the 5.2 release version.

There are bugs in other modules from time to time, but as for this problem. It is solved!
